accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit/', views.edit, name='edit'),
    path('password/', views.chg_pwd, name='chg_pwd'),
    path('delete/', views.delete, name='delete'),
    path('follow/<int:u_id>/', views.follow, name='follow'),
    path('profile/<str:name>/', views.profile, name='profile'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.new, name="new"),
    path('<int:b_id>/', views.detail, name="detail"),
    path('edit/<int:b_id>/', views.edit, name="edit"),
    path('delete/<int:b_id>/', views.delete, name="delete"),
    path('new_comment/<int:b_id>/', views.new_comment, name="new_comment"),
    path('del_comment/<int:c_id>/', views.del_comment, name="del_comment"),
    path('like/<int:b_id>/', views.like, name="like"),
    path('search/', views.search, name="search"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('boards.urls')),
    path('admin/', admin.site.urls),
]

boards/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_boards", blank=True)

    def __str__(self):
        return f"{self.id} {self.title}"


class Comment(models.Model):
    comment = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment
    

boards/forms.py
from django import forms
from .models import Board, Comment

class BoardForm(forms.ModelForm):
    
    class Meta:
        model = Board
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment'] # ('comment', ) # 튜플로 만들 때는 comma를 꼭 붙여줘야한다


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['comment'].widget.attrs.update(
            {'class':'form-control-sm', 'id':'abcdef'})

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Board, Comment
from .forms import BoardForm, CommentForm
from IPython import embed
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator

# Create your views here.
# -----------------------------------------------------------------------------
# index
# -----------------------------------------------------------------------------
def index(request):
    boards = Board.objects.all()

    # Paginator(전체리스트, 페이지당 보여지는 개수)
    paging = Paginator(boards, 5)
    page = request.GET.get('page')
    page_list = paging.get_page(page)

    context = {
        'boards': page_list
    }
    return render(request, 'boards/index.html', context)


# -----------------------------------------------------------------------------
# new
# -----------------------------------------------------------------------------
@login_required
def new(request):

    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.user = request.user
            board.save()
            return redirect('boards:detail', board.id)

    else:
        form = BoardForm()

    context = {
        'form': form
    }

    return render(request, 'boards/new.html', context)


# -----------------------------------------------------------------------------
# detail
# -----------------------------------------------------------------------------
def detail(request, b_id):
    board = get_object_or_404(Board, id=b_id)
    comment_form = CommentForm()
    # comments = board.comment_set.all()
    comments = Comment.objects.filter(board_id=b_id)
    # 팔로우 구현을 위해 person 정보 추가
    person = get_object_or_404(get_user_model(), id=board.user.id)
    context = {
        'board': board,
        'comment_form': comment_form,
        'comments': comments,
        'person': person,
    }
    return render(request, 'boards/detail.html', context)

    
# -----------------------------------------------------------------------------
# edit
# -----------------------------------------------------------------------------
@login_required
def edit(request, b_id):
    board = get_object_or_404(Board, id=b_id)

    if request.user != board.user:
        return redirect('boards:index')

    if request.method == 'POST':
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save()
            return redirect('boards:detail', board.id)

    else:
        form = BoardForm(instance=board)

    context = {
        'form' : form
    }

    return render(request, 'boards/edit.html', context)


# -----------------------------------------------------------------------------
# delete
# -----------------------------------------------------------------------------
@login_required
def delete(request, b_id):
    board = get_object_or_404(Board, id=b_id)

    if request.user != board.user:
        return redirect('boards:index')

    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')
    else:
        return redirect('boards:detail', board.id)


# -----------------------------------------------------------------------------
# new_comment
# -----------------------------------------------------------------------------
@login_required
@require_POST
def new_comment(request, b_id):
    form = CommentForm(request.POST)
    if form.is_valid:
        comment = form.save(commit=False)
        # comment.board = Board.objects.get(id=b_id)
        comment.board_id = b_id
        comment.user = request.user
        comment.save()

        return redirect('boards:detail', b_id)
    else:
        board = Board.objects.get(id=b_id)
        comments = board.comment_set.all()
        context = {
            'board': board,
            'comment_form': form,
            'comments': comments
        }

        return render(request, 'boards.detail.html', context)


# -----------------------------------------------------------------------------
# del_comment
# -----------------------------------------------------------------------------
@login_required
@require_POST
def del_comment(request, c_id):
    comment = get_object_or_404(Comment, id=c_id)
    b_id = comment.board_id
    if comment.user == request.user:
        comment.delete()

    return redirect('boards:detail', b_id)


# -----------------------------------------------------------------------------
# like
# -----------------------------------------------------------------------------
@login_required
def like(request, b_id):
    board = get_object_or_404(Board, pk=b_id)
    
    if board.like_users.filter(id=request.user.id).exists():
        board.like_users.remove(request.user)
    else:
        board.like_users.add(request.user)

    return redirect('boards:index')


# -----------------------------------------------------------------------------
# search
# -----------------------------------------------------------------------------
def search(request):
    text = request.GET.get('search')
    results = Board.objects.filter(title__contains=text)
    context = {
        'results': results
    }

    return render(request, 'boards/search.html', context)

boards/templates/boards/_board.html
<div class="card-body">
    <a href="{% url 'boards:like' board.id %}" class="card-link">
        <p class="card-text">
            {% if user in board.like_users.all %}
                <i class="fas fa-heart fa-lg" style="color:crimson;"></i>
            {% else %}
                <i class="far fa-heart fa-lg" style="color:black;"></i>
            {% endif %}
            {{ board.like_users.all|length }} 명이 좋아합니다.
        </p>
    </a>
</div>

boards/templates/boards/_follow.html
<div>
    </p>작성자 정보</p>
    <h2>{{ board.name }}</h2>
    <hr>
    {% if user != board.user %}
        {% if user in person.followers.all %}
            <a href="{% url 'accounts:follow' person.id %}">언팔로우</a>
        {% else %}
            <a href="{% url 'accounts:follow' person.id %}">팔로우</a>
        {% endif %}
    {% endif %}
    <div>
        팔로워: {{ person.followers.all|length }}
        팔로잉: {{ person.followings.all|length }}
    </div>

</div>

boards/templates/boards/_page.html
<nav>
    <ul class="pagination">
        {% if boards.has_previous %}
            <li class="page-item">
                <a href="{% url 'boards:index' %}?page={{ boards.previous_page_number }}" 
                    class="page-link">Prev</a>
            </li>
        {% endif %}

        {% for page_num in boards.paginator.page_range %}
            <li class="page-item {% if page_num == boards.number %}active{% endif %}">
                <a href="{% url 'boards:index' %}?page={{ page_num }}" class="page-link">{{ page_num }}</a>
            </li>
        {% endfor%}

        {% if boards.has_next %}
            <li class="page-item">
                <a href="{% url 'boards:index' %}?page={{ boards.next_page_number }}" class="page-link">Next</a>
            </li>
        {% endif %}
    </ul>
</nav>

boards/templates/boards/detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Detail{% endblock %}
{% block local_head_resources %}
{% endblock %}
{% block content %}
<div class="container">
    <h3>Detail</h3>
    <br>
    <table class="table">
        <tr>
            <th>타이틀</th>
            <td>{{ board.title}}</td>
        <tr>
        <tr>
            <th>내용</th>
            <td>  {{ board.content }}</td>
        <tr>
    </table>

    <br>
     <form action="{% url 'boards:delete' board.id %}" method="POST">
        <a href="{% url 'boards:index' %}" class="btn btn-primary">목록</a>

        {% if user == board.user %}
            <a href="{% url 'boards:edit' board.id %}" class="btn btn-warning">글 수정</a>
   
            {% csrf_token %}
            <a href="#" class="btn btn-danger"
                onclick="this.parentNode.submit()">글 삭제</a>
        {% endif %}
    </form>
    <hr>

    <!-- 팔로우 -->
    {% include 'boards/_follow.html' %}

    <br>
    <h4>댓글</h4>
    {% for comment in comments %}
        <p style="display:inline-block;">{{ comment.user }}: {{ comment.comment }}</p>
        {% if comment.user_id == user.id %}
        <form action="{% url 'boards:del_comment' comment.id %}" method="POST"  style="display:inline-block !important;">
            {% csrf_token %}
            <a href="#" onclick="this.parentNode.submit()" class="btn btn-secondary btn-sm"
               >댓글 삭제</a>
        </form>
        {% endif %}
        <br>
    {% empty %}
        <h5>댓글이 없습니다.</h5>
    {% endfor %}
    <hr>
    <form action="{% url 'boards:new_comment' board.id %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form comment_form %}
        {% buttons submit='댓글등록' %}{% endbuttons %}
    </form>


</div>
{% endblock %}
{% block local_body_resources %}
{% endblock %}

boards/templates/boards/edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Edit{% endblock %}
{% block local_head_resources %}
{% endblock %}
{% block content %}
<div class="container">
    <h3>Edit</h3>
    <hr>
    <form action="" method="POST">
        {%  csrf_token %}
        {{ form|crispy }}
        <br>
        <input type="submit" value="수정하기" class="btn btn-warning"/>
    </form>   
</div>
{% endblock %}
{% block local_body_resources %}
{% endblock %}

boards/templates/boards/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Index{% endblock %}
{% block local_head_resources %}
{% endblock %}
{% block content %}

<div class="container">
    <br>
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>user</th>
            <th></th>
        </tr>
    {% for board in boards %}
        <tr>
            <td>{{ board.id }}</td>
            <td><a href="{% url 'boards:detail' board.id %}">{{ board.title }}</a></td>
            <td><a href="{% url 'accounts:profile' board.user %}">{{ board.user }}</a></td>
            <td>{%  include 'boards/_board.html' %}</td>
        </tr>
    {% endfor %}
    </table>
    {% include 'boards/_page.html' %}
</div>

{% endblock %}
{% block local_body_resources %}
{% endblock %}

boards/templates/boards/new.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}New{% endblock %}
{% block local_head_resources %}
{% endblock %}
{% block content %}
<div class="container">
    <h3>New</h3>
    <hr>
    <form action="" method="POST">
        {%  csrf_token %}
        {{ form|crispy }}
        <br>
        <input type="submit" value="새 글 쓰기" class="btn btn-primary"/>
    </form>   
</div>
{% endblock %}
{% block local_body_resources %}
{% endblock %}

boards/templates/boards/search.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Search{% endblock %}
{% block local_head_resources %}
{% endblock %}
{% block content %}
<div class="container">
    <h3>검색 결과</h3>
    <hr>
    {% for board in results %}
        <li><a href="{% url 'boards:detail' board.id %}">{{ board.title }}</li>
    {% empty %}
     <p>검색 결과가 없습니다.<p>
    {% endfor%}
</div>
{% endblock %}
{% block local_body_resources %}
{% endblock %}