accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit/', views.edit, name='edit'),
    path('password/', views.chg_pwd, name='chg_pwd'),
    path('delete/', views.delete, name='delete'),
    path('follow/<int:u_id>/', views.follow, name='follow'),
    path('profile/<str:name>/', views.profile, name='profile'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.new, name="new"),
    path('<int:b_id>/', views.detail, name="detail"),
    path('edit/<int:b_id>/', views.edit, name="edit"),
    path('delete/<int:b_id>/', views.delete, name="delete"),
    path('new_comment/<int:b_id>/', views.new_comment, name="new_comment"),
    path('del_comment/<int:c_id>/', views.del_comment, name="del_comment"),
    path('like/<int:b_id>/', views.like, name="like"),
    path('search/', views.search, name="search"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('boards.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")

boards/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_boards", blank=True)

    def __str__(self):
        return f"{self.id} {self.title}"


class Comment(models.Model):
    comment = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment
    

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class UserCustomChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']


class UserCustomCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields
        

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model
from IPython import embed
from .forms import UserCustomChangeForm, UserCustomCreationForm
from django.contrib.auth.decorators import login_required


# Create your views here.
# -----------------------------------------------------------------------------
# signup
# -----------------------------------------------------------------------------
def signup(request):
    if request.user.is_authenticated:
        return redirect('boards:index')

    if request.method == 'POST':
        # User model을 재설정해서 해당 폼을 사용할 수 없음
        # form = UserCreationForm(request.POST)
        # 새롭게 정의한 폼으로 변경
        form = UserCustomCreationForm(request.POST)
        #embed()
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('boards:index')
    else:
        # form = UserCreationForm()
        form = UserCustomCreationForm()
        #embed()

    context = {
        'form': form,
        'label': '회원가입'
    }
    return render(request, 'accounts/signup.html', context)


# -----------------------------------------------------------------------------
# login
# -----------------------------------------------------------------------------
def login(request):
    if request.user.is_authenticated:
        return redirect('boards:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'boards:index')
    else:
        form = AuthenticationForm()

    context = {
        'form': form,
        'label': '로그인'
    }

    # return render(request, 'accounts/auth_form.html', context)
    return render(request, 'accounts/login.html', context)


# -----------------------------------------------------------------------------
# logout
# -----------------------------------------------------------------------------
@login_required
def logout(request):
    if request.method == 'POST':
        auth_logout(request)

    return redirect('boards:index')


# -----------------------------------------------------------------------------
# edit
# -----------------------------------------------------------------------------
@login_required
def edit(request):
    if request.method == 'POST':
        form = UserCustomChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('boards:index')
    else:
        form = UserCustomChangeForm(instance=request.user)

    context = {
        'form': form,
        'label': '회원 정보 수정'
    }

    return render(request, 'accounts/auth_form.html', context)


# -----------------------------------------------------------------------------
# chg_pwd
# -----------------------------------------------------------------------------
@login_required
def chg_pwd(request):

    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('accounts:edit')

    else:
        form = PasswordChangeForm(request.user)

    context = {
        'form': form,
        'label': '비밀번호 수정'
    }

    return render(request, 'accounts/auth_form.html', context)


# -----------------------------------------------------------------------------
# delete
# -----------------------------------------------------------------------------
@login_required
def delete(request):
    if request.method == 'POST':
        request.user.delete()

    return redirect('boards:index')


# -----------------------------------------------------------------------------
# follow
# -----------------------------------------------------------------------------
@login_required
def follow(request, u_id):
    person = get_object_or_404(get_user_model(), id=u_id)

    if person.followers.filter(id=request.user.id).exists():
        person.followers.remove(request.user)
    else:
        person.followers.add(request.user)

    return redirect('boards:index')
    

# -----------------------------------------------------------------------------
# profile
# -----------------------------------------------------------------------------
def profile(request, name):
    person = get_object_or_404(get_user_model(), username=name)
    context = {
        'person': person
    }
 
    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/auth_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}{% endblock %}
{% block local_head_resources %}
{% endblock %}
{% block content %}
<div class="container">
    <h3>{{ label }}</h3>
    <hr>
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% if request.resolver_match.url_name == 'signup' %}
            {% buttons submit="회원가입" %}{% endbuttons%}
        {% elif request.resolver_match.url_name == 'login' %}
            {% buttons submit="로그인" %}{% endbuttons%}
        {% elif request.resolver_match.url_name == 'edit' %}
            {% buttons submit="수정하기" %}{% endbuttons%}
        {% else %}
            {% buttons submit="비번 수정" %}{% endbuttons%}
        {% endif %}
    </form>
    {% if request.resolver_match.url_name == 'edit' %}
        <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token%}
            <a href="#" onclick="this.parentNode.submit()" class="btn btn-danger">회원 탈퇴</a>
        </form>
    {% endif %}
</div>
{% endblock %}
{% block local_body_resources %}
{% endblock %}

accounts/templates/accounts/edit.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}User Edit{% endblock %}
{% block local_head_resources %}
{% endblock %}
{% block content %}
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit="정보수정" %}
        {% endbuttons %}
    </form>
</div>
{% endblock %}
{% block local_body_resources %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% load socialaccount %}
{% block title %}Login{% endblock %}
{% block local_head_resources %}
{% endblock %}
{% block content %}
<div class="container">
    <h3>로그인</h3>
    <hr>
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit="로그인" %}
        {% endbuttons %}
    
        <!--
        {#% buttons submit="회원가입_2" reset="다시입력" %}
        {#% endbuttons %}
        -->
    </form>
    <a href="{% provider_login_url 'kakao' method='oauth2' %}" class="btn btn-warning">카카오 로그인</a>
    <a href="{% provider_login_url 'naver' method='oauth2' %}" class="btn btn-success">네이버 로그인</a>
</div>


{% endblock %}
{% block local_body_resources %}
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}
{% block local_head_resources %}
{% endblock %}
{% block content %}
<div class="jumbotron text-center text-white bg-dark">
    <h1 class="display-4"><i>{{ person.username }}</i>님의 프로필</h1>
    <h4 class="border-white">
        <p class="lead">
            팔로워: {{ person.followers.all|length }}
            팔로잉: {{ person.followings.all|length }}
        </p>
        {% if user != person %}
            {% if user in person.followers.all %}
                <a class="btn btn-danger btn-lg" href="{% url 'accounts:follow' person.id %}">언팔로우</a>
            {% else %}
                <a class="btn btn-primary btn-lg" href="{% url 'accounts:follow' person.id %}">팔로우</a>
            {% endif %}
        {% endif %}
    </h4>
</div>
<div class="container">
    <h3 class="text-cent"><i>{{ person.username }}</i>님이 작성한 글 리스트</h3>
    <div class="row">
        {% for board in person.board_set.all %}
            <div class="col-4 my-2">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ board.title }}</h5>
                        <p class="card-text">{{ board.comment_set.all|length }}개의 댓글</p>
                        <p class="card-text">{{ board.like_users.all|length }}하트</p>
                        <a href="{% url 'boards:detail' board.id %}" class="btn btn-primary">자세히 보기</a>
                    </div>
                </div>
            </div>
        {% empty %}
        {% endfor %}
    </div>
    <hr>
    <h3 class="text-cent"><i>{{ person.username }}</i>님이 작성한 댓글 리스트</h3>
    <div class="row">
        {% for com in person.comment_set.all %}
        <div class="col-12 my-2">
            <div class="card">
                <div class="card-body">
                    <blockquote class="blockquote">
                        <p class="mb-0">{{ com.board }}</p>
                        <footer class="blockquote-footer">{{ com.comment }}</footer>
                    </blockquote>
                </div>
            </div>
        </div>
        {% endfor%}
    </div>
</div>

{% endblock %}
{% block local_body_resources %}
{% endblock %}

accounts/templates/accounts/pwd.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}User PWD Edit{% endblock %}
{% block local_head_resources %}
{% endblock %}
{% block content %}
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit="비밀번호 수정" %}
        {% endbuttons %}
    </form>
</div>
{% endblock %}
{% block local_body_resources %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Sign Up{% endblock %}
{% block local_head_resources %}
{% endblock %}
{% block content %}
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">회원가입</button>
        {% endbuttons %}
        <!--
        {#% buttons submit="회원가입_2" reset="다시입력" %}
        {#% endbuttons %}
        -->
    </form>
</div>
{% endblock %}
{% block local_body_resources %}
{% endblock %}