accounts/urls.py
from django.urls import path
from . import views


app_name = "accounts"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('edit/', views.edit, name='edit'),
    path('password/', views.chg_pwd, name='chg_pwd'),
    path('delete/', views.delete, name='delete'),
    path('follow/<int:u_id>/', views.follow, name='follow'),
    path('profile/<str:name>/', views.profile, name='profile'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.new, name="new"),
    path('<int:b_id>/', views.detail, name="detail"),
    path('edit/<int:b_id>/', views.edit, name="edit"),
    path('delete/<int:b_id>/', views.delete, name="delete"),
    path('new_comment/<int:b_id>/', views.new_comment, name="new_comment"),
    path('del_comment/<int:c_id>/', views.del_comment, name="del_comment"),
    path('like/<int:b_id>/', views.like, name="like"),
    path('search/', views.search, name="search"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('boards.urls')),
    path('admin/', admin.site.urls),
]

config/templates/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Boards</a>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'boards:index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <p class="nav-link">안녕하세요, </p>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:profile' user.username %}">{{ user.username }}</a>
        </li>
        <li class="nav-item">
            <a class="btn btn-warning btn-sm" href="{% url 'accounts:edit' %}">정보수정</a>
        </li>
        <li class="nav-item">
            <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <a class="btn btn-danger btn-sm" href="#" onclick="this.parentNode.submit()">로그아웃</a>
            </form>
        </li>
        {% endif %}
        <!--
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
        -->

        </ul>
        <form class="form-inline my-2 my-lg-0name=" action="{% url 'boards:search' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" >
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

config/templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <!-- global resources -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'boards/css/global.css' %}"/>

    <!-- local resources-->
    {% block local_head_resources %}
    {% endblock %}
</head>
<body>
    {% include '_nav.html' %}
    <div class="container">
        {% if user.is_authenticated %}
            <a href="{% url 'boards:new' %}" class="btn btn-primary">New</a>
            <br><br>
        {% else %}
            {% if request.resolver_match.url_name == 'index' %}
                <h4><i>로그인 </i>하셔야 새 글을 작성하실 수 있습니다.</h4>
            {% endif %}
            <a href="{% url 'accounts:signup' %}" class="btn btn-info">회원가입</a>
            <a href="{% url 'accounts:login' %}" class="btn btn-info">로그인</a>
            <br><br>
        {% endif %}
    </div>

    {% block content %}
    {% endblock %}

    <!-- globla body resources-->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/2f1062726d.js" crossorigin="anonymous"></script>

    <!-- local body resources -->
    {% block local_body_resources %}
    {% endblock %}
</body>
</html>